project:
  type: book 
  output-dir: docs
book:
  title: "Land Use Demonstrators"
  author: "Anna Zanchetta"
  date: today
  search: true
  repo-url: https://github.com/ciupava/LandUseDemonstrator/tree/main/docs
  downloads: [pdf]
  chapters:
    - index.qmd
    - intro.qmd
    - notes.qmd
    - data_sources.qmd
    # - jobacc.qmd
    # - part: "Running TPI"
    #   chapters:
    #     - data.qmd
    #     - data_prep.qmd
    #     - workflow.qmd


format:
  html:
    # theme: cosmo
    theme:
      light: flatly
      dark: darkly
    # css: styles.css
    toc: true
