project:
  type: website 
  output-dir: slides
# book:
#   title: "TPI Target Population Index"
#   search: true
#   repo-url: https://github.com/ciupava/TPI/tree/master/docs
#   downloads: [pdf]
#   chapters:
#     - index.qmd
#     - jobacc.qmd
#     - part: "Running TPI"
#       chapters:
#         - data.qmd
#         - data_prep.qmd
#         - workflow.qmd
   
# format:
#  html:
#    theme: cosmo


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
