project:
  type: website 
  output-dir: docs
book:
  title: "Land Use Demonstrators"
  search: true
  repo-url: https://github.com/ciupava/LandUseDemonstrator/tree/main/docs
  downloads: [pdf]
  chapters:
    - notes.qmd
    # - jobacc.qmd
    # - part: "Running TPI"
    #   chapters:
    #     - data.qmd
    #     - data_prep.qmd
    #     - workflow.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
