project:
  type: book 
  output-dir: docs
execute:
  freeze: true
book:
  title: "L(O)UD"
  subtutle: "Land Use Demonstrator project"
  author: "Anna Zanchetta"
  date: today
  search: true
  repo-url: https://github.com/ciupava/LandUseDemonstrator/tree/main/docs
  downloads: [pdf]
  chapters:
    - index.qmd
    - intro.qmd
    - data_sources.qmd
    - notes.qmd

format:
  html:
    # theme: cosmo
    theme:
      light: flatly
      dark: darkly
    # css: styles.css
    toc: true
