
# Data Sources

## Comprehensive tables

**Table 1 - **4 indicators and data we use to quantify them:
 
| real (X) VS estimated (O)| Indicator | Definition |Data source | Link |
|:-:|-|-|-|-|
|O| Mobility emissions | | gov uk data estimates <br/>*at LAD level* (only) |  |
|O| Greenspace accessibility | | OS greenspace layer | [link]()|
|O| Jobs accessibility| n. jobs within certain time interval by transport mode| to be created| | 
|X| House prices | Median house prices for administrative geographies|ONS| [2022 data](https://www.ons.gov.uk/peoplepopulationandcommunity/housing/bulletins/housepricestatisticsforsmallareas/yearendingmarch2022)|

---

**Table 2 - ** Indicators (columns) and plausible explanatory/building variables (rows - landuse variables)

| _Variables_ | Mobility emissions | Greenspace<br/> acc | Jobs acc | House<br/> prices | _Sources_ |
|-|:-:|:-:|:-:|:-:|-|
| n. of trips| X | | | | OD data (Nomis)|
| distance  | X | | | | OD data (Nomis)|
| mode transport| X | | | | OD data (Nomis)|
| distance to access point |  | X |  | X | from OS layer |
| areal extension of gs |  | X |  | X | from OS layer |
| n. available jobs |  |  | X | X | NA |
| distance to employment center |  |  | X | X | 
| access to public transport |  |  | X | X |

... distinguish landuse as explanatory variable from landuse as indicator...

## List of sources

Data hunting still in progress, to be filled up when data use is certain.<br/>
See [notes](notes.qmd) to follow the development.

### gov.uk

...


### CDRC

...


### Time Use Survey

Time Use Survey for UK is available from UK Data Service website at [http://dx.doi.org/10.5255/UKDA-SN-8128-1](http://dx.doi.org/10.5255/UKDA-SN-8128-1)

---

