# Notes

## September

**Exploratory phase**

The idea is to focus on a few indicators (one or two) in order generate a *methodology* to apply to different variables (IE all the rest of indicators)

Concentrating on Indicators for [Net-zero a and b](intro.qmd#net-zero):

- a. *mobility based emissions* ... integration with SPC $/$ AB-street?

OD flows from UK census


- b. *housing based emissions*



### Data availability

---

- Generated list of possible data sources with metadata, resolution, website (when available), etc (local on laptop not online)

we can get from gov CO<sub>2</sub>)e (carbon dioxide equivalent) data for several activities (occupations) and travel modes, including transport, freight, etc [link](https://www.gov.uk/government/statistical-data-sets/stacked-electricity-consumption-statistics-data)

[UK data service?](https://ukdataservice.ac.uk/find-data/browse/)

- a. *mobility based emissions*
UK GHG emissions national statistics [Data for 2005 - 2020](https://www.gov.uk/government/statistics/uk-local-authority-and-regional-greenhouse-gas-emissions-national-statistics-2005-to-2020)

- b. *housing based emissions*
UK GHG emissions national statistics [Sub-national electricity consumption d for 2010 - 2020](https://www.gov.uk/government/statistical-data-sets/stacked-electricity-consumption-statistics-data)

### Did someone already do this?

---

[carbon.place](https://www.carbon.place/)

Project from Malcom Morgan (Univ of Leeds) ...

> The PBCC estimates the average carbon footprint per person for each LSOA in England


**NOTE:**

cool project, GitHub code available but not reproducible (?)

opened issue here [https://github.com/creds2/CarbonCalculator/issues/6](https://github.com/creds2/CarbonCalculator/issues/6)




## October

---

x x  x

---

### Open questions
*And plausible answer*

---

- [ ] Resolution - LSOAS/ MSOAS? *feedback from Dani regarding SS*
depending on how available data are aggregated

- [ ] type of output - *map, web ...* ~~MapBox~~ *MapLibre GL, Leaflet, ...*

- [ ] how to generate scenarios - *ideas: change parameters' range, run ABstreet simulations...?*

- [ ] how turn on/off scenarios in the visualisation- *different layers in the map*

- [ ] integrate with SPC -  *need to integrate more Census variables? feasible?*

- [ ] can we actually build a methodology, given the different range of indicators and data?

- [X] importance of localised emissions and need for air-flow modelling ... *not relevant for GHG*


---

### Trying to link to map

Let's see if [this map link](map.html) works 



