# Data sources

This page tabulates and provides links to all data sources used in this project.
For more details on how each dataset is used and processed, refer to the [Methodology](method.qmd) section.

## Project-wide

- Ordnance Survey (OS) | 2011 Census Output Areas | [link](https://geoportal.statistics.gov.uk/datasets/ons::output-areas-dec-2011-boundaries-ew-bgc/about)

## Accessibility indicators

- Office for National Statistics (ONS) | Population Weighted Centroids (PWC) of Output Areas | [link](https://www.ons.gov.uk/census/2001censusandearlier/dataandproducts/outputgeography/outputareas)
- ONS | Workplace zones | [link](https://www.nomisweb.co.uk/sources/census_2011_wp)
- OS | Open Greenspace  | [link](https://beta.ordnancesurvey.co.uk/products/os-open-greenspace)
- OpenStreetMap (OSM) | OpenStreetMap network data | [link](https://openstreetmap.org)
- Institute for Transport Studies, University of Leeds | UK GTFS data | [link](https://itsleeds.github.io/UK2GTFS/)

## Air quality

- Department for Environment, Food and Rural Affairs (DEFRA) | UK AIR | [link](https://uk-air.defra.gov.uk/data/pcm-data)

## House prices

- Chi et al. | A new attribute-linked
residential property price dataset for England and Wales 2011-2019 | [link](https://doi.org/10.5255/UKDA-SN-854240)

## Explanatory variables for modelling

- ONS | Population estimates | [link](https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/censusoutputareaestimatesinthenortheastregionofengland/mid2020sape23dt10d/sape23dt10dmid2020coaunformattedsyoaestimatesnortheast.xlsx)
- ONS | Workplace population | [link](https://www.nomisweb.co.uk/sources/census_2011_wp)
- Copernicus | CORINE Land Cover classification | [link](https://land.copernicus.eu/pan-european/corine-land-cover)
- The Alan Turing Institute | Spatial Signatures of Great Britain | [link](https://urbangrammarai.xyz/story/)
